### ISSUE TITLE
react-native sample is useless

### ISSUE THREAD

**Issue by YeomanYe** [getsentry/examples#17]
When i use command of 'yarn start' to debug project.The bug appear, that is detail:

Loading dependency graph...(node:2200) UnhandledPromiseRejectionWarning: Error: `fsevents` unavailable (this watcher can only be used on Darwin)
    at new FSEventsWatcher (/Users/madecare/Downloads/react-native/AwesomeProject/node_modules/sane/src/fsevents_watcher.js:41:11)
    at createWatcher (/Users/madecare/Downloads/react-native/AwesomeProject/node_modules/metro/node_modules/jest-haste-map/build/index.js:572:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/madecare/Downloads/react-native/AwesomeProject/node_modules/metro/node_modules/jest-haste-map/build/index.js:683:44)
    at _buildPromise._buildFileMap.then.then.hasteMap (/Users/madecare/Downloads/react-native/AwesomeProject/node_modules/metro/node_modules/jest-haste-map/build/index.js:280:21)
(node:2200) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2200) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by filipef101** [comment]
Yeah, can anyone update it?

**Comment by bruno-garcia** [comment]
There's a pretty up-to-date example here now, on the repo, which we use to develop:

https://github.com/getsentry/sentry-react-native/tree/master/sample

But we'll keep this issue open to update the example here.

**Comment by filipef101** [comment]
Or remove and point to that 🙂

**Comment by bruno-garcia** [comment]
Anyone willing to contribute with a PR 🙏 ?

**Comment by armcknight** [comment]
We are deprecating this repository in favor of sample projects like @bruno-garcia pointed out above. I'm closing this issue, and we will archive this repository in the near future. Hope the other sample project worked for you (I realize this issue is quite old now) but don't hesitate to open issues against https://github.com/getsentry/sentry-react-native for anything you need! Thanks 🙏🏻
